# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='duration',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
