# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_hours',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
